data:
  train_data_path: "./train_data.npy"

data_split:
  test_size: 0.2
  random_state: 42

device: "cuda"       # or "cpu"

optimizer:
  lr: 0.01
  momentum: 0.9

training:
  epochs: 3

activation_functions: ["relu", "tanh", "sigmoid"]

bayesian_opt:
  batch_size: [16, 256]          # search range
  activation_index: [0, 2]       # indices into activation_functions
  init_points: 5
  n_iter: 15
  random_state: 42
  verbose: 2